### ISSUE TITLE
Shot data inferred stats

### ISSUE THREAD

**Issue by nimberledge** [nimberledge/akm-xg#3]
Create a workflow to take the location info from the shot_data.json to infer two additional columns - 
1. Distance to goal (use distance to center of the goal, coords (120, 40))
2. Angle subtended by goalposts (draw a line to either goalpost, calculate the angle between them) (goals are 8 yards wide)

Additionally, filter the json file to get only shots from open play, as set pieces (FKs/penalties) will have to be treated differently, with a different xG model.

**Comment by tsnl** [comment]
Changes to data pipeline
- All scripts depend on the [StatsBomb Open-Data Dataset](https://github.com/statsbomb/open-data) being located at `/data/open-data-master`. This replaces hard-coded paths that were unique to @nimberledge's file-system.
- `ExtractShotData.jl` now produces either CSV or JSON, accepts different arguments. Example of new usage:
  
  ```
  $ julia scripts/ExtractShotData.jl json     # outputs the JSON file 'data/shot_data.json'
  $ julia scripts/ExtractShotData.jl csv      # outputs the CSV file 'data/shot_data.csv
  ```
